apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fetch-supplier-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIND-DEMO"
    executables.ai.sap.com/description: "Fetches supplier data from Northwind service"
    executables.ai.sap.com/name: "NORTHWIND Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: fetch-supplier-data-pipeline
  templates:
    - name: fetch-supplier-data-pipeline
      script:
        image: python:3.8
        command: ["python"]
        source: |
          pip install requests
          python - <<EOF
          import requests

          def fetch_suppliers():
              # OData Service URL
              url = "https://services.odata.org/northwind/northwind.svc/Suppliers?$format=json"

              try:
                  # Send GET request to fetch supplier data
                  response = requests.get(url)
                  response.raise_for_status()  # Raise an error for HTTP errors

                  # Parse JSON response
                  data = response.json()
                  suppliers = data.get("value", [])
                  # suppliers = data

                  # Display supplier data
                  print("Supplier Data:")
                  for supplier in suppliers:
                      print(f"ID: {supplier['SupplierID']}, Name: {supplier['CompanyName']}, Country: {supplier['Country']}")

              except Exception as e:
                  print(f"Error fetching supplier data: {e}")

          if __name__ == "__main__":
              fetch_suppliers()
          # print("fetch_suppliers.py")
      volumeMounts:
        - name: script-volume
          mountPath: /mnt/scripts
  volumes:
    - name: script-volume
      configMap:
        name: fetch-suppliers-script
