apiVersion: ai.sap.com/v1alpha1
kind: TaskTemplate
metadata:
  name: fetch-supplier-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIND-DEMO"
    executables.ai.sap.com/description: "Greets the user"
    executables.ai.sap.com/name: "NORTHWIND Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  description: "Fetch and process data from the Northwind service."
  artifact:
    type: python
    reference: fetch_suppliers.py
  arguments: {}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
