apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fetch-supplier-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIND-DEMO"
    executables.ai.sap.com/description: "Fetches supplier data from Northwind service"
    executables.ai.sap.com/name: "NORTHWIND Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: fetch-supplier-data-pipeline
  templates:
    - name: fetch-supplier-data-pipeline
      script:
        image: python:3.8
        command: ["python"]
        source: |
          import os
          import sys

          # Ensure the /tmp directory exists
          if not os.path.exists('/tmp'):
              os.makedirs('/tmp')

          # Simulate fetching supplier data and writing to a file
          supplier_data = "Supplier data from Northwind service"
          with open('/tmp/supplier-output.txt', 'w') as f:
              f.write(supplier_data)
          print("Supplier data fetched and written to /tmp/supplier-output.txt")
      volumeMounts:
        - name: script-volume
          mountPath: /mnt/scripts
      outputs:
        parameters:
          - name: supplier-output
            valueFrom:
              path: /tmp/supplier-output.txt
  volumes:
    - name: script-volume
      configMap:
        name: fetch-suppliers-script
