apiVersion: ai.sap.com/v1alpha1
kind: pipeline
metadata:
  name: fetch-supplier-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIND-DEMO"
    executables.ai.sap.com/description: "Greets the user"
    executables.ai.sap.com/name: "NORTHWIND Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entryPoint: mypipeline
  arguments:
    parameters:
      - name: script-path
        value: "/workspace/fetch_suppliers.py"
  templates:
    - name: mypipeline
      container:
        image: python:3.8
        command: ["python"]
        args: ["{{workflow.parameters.script-path}}"]
        workingDir: /workspace
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          volumeMounts:
          - name: workspace-volume
            mountPath: /workspace
  volumes:
    - name: workspace-volume
      emptyDir: {}
