apiVersion: ai.sap.com/v1alpha1
kind: TaskTemplate
metadata:
  name: northwind-task
  namespace: default
spec:
  description: "Task to fetch and process data from the Northwind OData service."
  runtime:
    name: python:3.8  # Specify the Python runtime to execute the script
  entrypoint: northwind_processor.py  # Specify the main Python file in the repository
  artifact:
    type: git
    repository:
      url: "https://github.com/Priya041199/AI-DEMO"  # Replace with your Git repo URL
      branch: "main"  # Specify the branch to pull
      path: "/"  # Path to the script in the repo root; adjust if necessary
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
  environment:
    variables:
      - name: NORTHWIND_ENDPOINT
        value: "https://services.odata.org/V3/Northwind/Northwind.svc/Products"
