apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline12
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "DEMO-TUTORIAL"
    executables.ai.sap.com/description: "Greets the user"
    executables.ai.sap.com/name: "Test Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: greet
        template: greeter

  - name: greeter
    container:
      image: docker.io/python:latest
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/fetch_suppliers.py"
        # - "fetch_suppliers.py"
      resources:
          requests:
            cpu: "1"
            memory: "1Gi"
          
