apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pipeline12
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIN-AI-SCENE"
    executables.ai.sap.com/description: "NORTHWIND-SCENE-DESC"
    executables.ai.sap.com/name: "Test NORTHWIND"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: fetch-supplier-data-pipeline
  templates:
  - name: fetch-supplier-data-pipeline
    container:
      image: docker.io/python:latest
      command:
        - python3
        - '-c'
      args:
        - |
         "python /app/src/fetch_suppliers.py"
        # - "fetch_suppliers.py"
       # - | 
       #    import os 
       #    dir_path = os.path.dirname(os.path.realpath(__file__))
       # - |
       #  print("Hello World")
    resources:
        requests:
        cpu: "1"
        memory: "1Gi"
    outputs:
      artifacts:
      - name: supplier-data
        path: /app/src/supplier_data.json
