apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: fetch-supplier-data-pipeline
  annotations:
    scenarios.ai.sap.com/description: "Introduction to SAP AI Core"
    scenarios.ai.sap.com/name: "NORTHWIND-DEMO"
    executables.ai.sap.com/description: "Greets the user"
    executables.ai.sap.com/name: "NORTHWIND Pipeline"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entryPoint: fetch-supplier-data-pipeline
  templates:
    - name: fetch-supplier-data-pipeline
      script:
        runtime: python:3.8
        entryPoint:
          fetch-supplier-data-pipeline:
            command: ["python", "fetch_suppliers.py"]
        resources:
          requests:
            cpu: "1"
            memory: "1Gi"
